title: Escophele Phele
email: hey@escophele.com
description:
baseurl: ""
url: ""
permalink: /:title
paginate: 7
paginate_path: "/:num"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
