title: Escophele Bee
email: hey@escophele.com
description: 
baseurl: ""
url: ""
permalink: /:year/:month/:day/
paginate: 5

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"